### PR TITLE
Deploy portfolio page

### PR DESCRIPTION
**Pull request by bhushan354**
- Deployed the project using github pages .
- Updated README.md file .

Thank you ,
Bhushan.

### CODE REVIEW

**Review by levy002 — APPROVED** [review]
## Hello @bhushan354 
 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

  unnamed


## Highlights
- No linter errors :heavy_check_mark: 
- Your deployed websites look fine as expected :heavy_check_mark: 
 
## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bhushan354** [comment]
Hello sir @levy002 ,
you did aproved my project but made a comment that i need to make some changes.
thats kind a confusing to me .
can you please elaborate about that ? 

Thank you ,
Bhushan .

**Comment by levy002** [comment]
> Hello sir @levy002 , you did aproved my project but made a comment that i need to make some changes. thats kind a confusing to me . can you please elaborate about that ?
> 
> Thank you , Bhushan .

Thank you for raising this issue @bhushan354 . It's my mistake. You project is approved, You can merge it now.

**Comment by bhushan354** [comment]
thanks sir

**Pull request merged**
